AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Functions

  Sample SAM Template for Functions
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  Signup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Signup/
      Handler: app.signupHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  Login:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Login/
      Handler: app.loginHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  ResetPassword:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ResetPassword/
      Handler: app.passwordHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  SignupSecurityQuestions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SignupSecurityQuestions/
      Handler: app.signupSecurityHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  ValidateSecurityQuestions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ValidateSecurityQuestions/
      Handler: app.signinSecurityHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  Notifications:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Notifications/
      Handler: app.notificationsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  AddQuestions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Questions/
      Handler: app.addQuestionHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  EditQuestions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Questions/
      Handler: app.editQuestionHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  DeleteQuestions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Questions/
      Handler: app.deleteQuestionHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  FilterQuestions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Questions/
      Handler: app.filterQuestionsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  AddCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Categories/
      Handler: app.addCategoryHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  GetCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Categories/
      Handler: app.getCategoriesHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  DeleteCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Categories/
      Handler: app.deleteCategoryHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  Game:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Game/
      Handler: app.gameHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  GetGames:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Game/
      Handler: app.getGamesHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  GetQuestionsForGame:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Questions/
      Handler: app.getQuestionsForGameHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
